# Generated by Django 5.2.17 on 2026-09-25 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(db_index=True, max_length=200)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("sex", models.CharField(blank=True, max_length=30)),
                (
                    "program",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("semester", models.CharField(blank=True, max_length=20)),
                ("city_origin", models.CharField(blank=True, max_length=120)),
                ("city_current", models.CharField(blank=True, max_length=120)),
                ("lives_with", models.CharField(blank=True, max_length=120)),
                ("first_generation", models.CharField(blank=True, max_length=60)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="RiskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField(default=0)),
                ("total_max", models.IntegerField(default=0)),
                ("total_pct", models.FloatField(default=0.0)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                        ],
                        db_index=True,
                        default="bajo",
                        max_length=10,
                    ),
                ),
                ("dimensions", models.JSONField(blank=True, default=list)),
                ("items", models.JSONField(blank=True, default=list)),
                ("alerts", models.JSONField(blank=True, default=list)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="analysis.student",
                    ),
                ),
            ],
        ),
    ]
